server:
  port: 10000
spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: thirdgateway
          uri: lb://thirdgateway
          predicates:
            - Path=/thirdgateway/**
          filters:
            - StripPrefix=1

logging:
  gelf:
    ip: 127.0.0.1
    port: 12201
  file: classpath:logback-spring.xml