server:
  port: 10005
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  datasource:
    tomcat:
      max-wait: 14400
      max-active: 500
      min-idle: 2
      initial-size: 10
    username: postgres
    password: TpzS5zHVnPSF
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.102:10101/saas-dev?useSSL=false&seUnicode=true&characterEncoding=UTF-8
    platform: postgres
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.1.102
    port: 10102
    username: admin
    password: admin
    virtual-host: ${spring.profiles.active}
  redis:
    jedis:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 250
    timeout: 2000
    password:
    port: 10103
    host: 192.168.1.102
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.ve.user.dal.entity
logging:
  gelf:
    ip: 127.0.0.1
    port: 12201
  file: classpath:logback-spring.xml
