server:
  port: 10003
spring:
  datasource:
    tomcat:
      max-wait: 14400
      max-active: 500
      min-idle: 2
      initial-size: 10
    password: ve2021.Ve
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.104:10101/local?useSSL=false&seUnicode=true&characterEncoding=UTF-8
    platform: postgres
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.1.104
    port: 10102
    username: admin
    password: admin
    virtual-host: ${spring.profiles.active}
  redis:
    jedis:
      pool:
        min-idle: 2
        max-idle: 10
        max-active: 250
    timeout: 2000
    password:
    port: 10103
    host: 192.168.1.104
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.ve.thirdgateway.dal.entity
baidu:
  ak: 1
  sk: 1
ali:
  sms:
    access-key-id: 1
    access-key-secret: 1
  app-key: 1
  app-secret: 1
wechat:
  url:
    jscode2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
    access_token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid={0}&secret={1}
  miniprogram:
    appid: 1
    secret: 1
  official-account:
    appid: 1
    secret: 1
    message:
      template-id: 1
  callback:
    token: 1
    encoding-AES-Key: 1
